stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t myapp .
  artifacts:
    paths:
      - /app/myapp.tar

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker load -i myapp.tar
    - docker run --rm myapp pytest
