version: '3'
services:
  weather-bot:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
        labels: "mylabel"
        env: "prod"
        tag: "latest"
        path: "./weather-bot.log"
